package com.dao;

import com.app.Chart;
import com.app.ChartEntry;
import com.util.Database;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.stream.IntStream;

// charts table;
// CREATE TABLE charts(
//        id INTEGER NOT NULL PRIMARY KEY,
//        artist_id INTEGER NOT NULL REFERENCES artists(id),
//        album_id INTEGER NOT NULL REFERENCES albums(id),
//        position INTEGER
// );


public class ChartController {

    public boolean create(int artistID, int albumID, int position) {
        boolean returnValue = true;
        try(PreparedStatement preparedStatement = Database.getConnection().prepareStatement("INSERT INTO charts VALUES(0, ?, ?, ?)")) {
            // ID value generated by DBMS
            preparedStatement.setInt(1, artistID);
            preparedStatement.setInt(2, albumID);
            preparedStatement.setInt(3, position);
            if(preparedStatement.executeUpdate() == 0) {
                returnValue = false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return returnValue;
    }

    public ChartEntry findByPosition(int position) {
        ChartEntry entry = null;

        try(Statement statement = Database.getConnection().createStatement()) {
            ResultSet rs = statement.executeQuery("SELECT * FROM charts WHERE position = " + position);
            rs.next();
            entry = new ChartEntry(rs.getInt(1), rs.getInt(2),
                                   rs.getInt(3), rs.getInt(4));
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return entry;
    }

    public Chart getChart() {
        Chart chart = new Chart();
        ChartEntry entry;

        try (Statement statement = Database.getConnection().createStatement()) {
            ResultSet resultSet = statement.executeQuery("SELECT * FROM charts ORDER BY position");
            while (resultSet.next()) {
                entry = new ChartEntry(resultSet.getInt(1), resultSet.getInt(2),
                                       resultSet.getInt(3), resultSet.getInt(4));
                chart.add(entry);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return chart;
    }

}
