package com.dao;

import com.app.Album;
import com.app.Artist;
import com.util.Database;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;

public class AlbumController {

    public boolean create(String name, int artistID, int releaseYear) {
        boolean returnValue = true;
        try (PreparedStatement statement = Database.getConnection()
                .prepareStatement("INSERT INTO albums VALUES(0, ?, ?, ?)")) {
            // ID value generated by DBMS
            statement.setString(1,
                                name);
            statement.setInt(2,
                             artistID);
            statement.setInt(3,
                             releaseYear);
            if (statement.executeUpdate() == 0) {
                returnValue = false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return returnValue;
    }

    public List<Album> findByArtist(int artistID) {
        List<Album> albums = new ArrayList<>();

        try (Statement statement = Database.getConnection()
                .createStatement()) {
            Album album;
            ResultSet rs = statement.executeQuery("SELECT * FROM albums WHERE artist_id = " + artistID);
            while (rs.next()) {
                album = new Album(rs.getInt(1),
                                  rs.getString(2),
                                  rs.getInt(3),
                                  rs.getInt(4));
                albums.add(album);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return albums;
    }

    public List<Album> findByName(String name) {
        List<Album> albums = new ArrayList<>();

        try (Statement statement = Database.getConnection()
                .createStatement()) {
            Album album;
            ResultSet rs = statement.executeQuery("SELECT * FROM albums WHERE name = '" + name + "'");
            while (rs.next()) {
                album = new Album(rs.getInt(1),
                                  rs.getString(2),
                                  rs.getInt(3),
                                  rs.getInt(4));
                albums.add(album);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return albums;
    }

    public Album findByID(int albumID) {
        Album album = null;

        try(Statement statement = Database.getConnection().createStatement()) {
            ResultSet resultSet = statement.executeQuery("SELECT * FROM albums WHERE id = " + albumID);
            resultSet.next();
            album = new Album(albumID, resultSet.getString(2), resultSet.getInt(3), resultSet.getInt(4));
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return album;
    }

    public Album findLastAddedAlbum() {
        Album album = null;
        String query = "SELECT * " +
                "FROM (SELECT * FROM albums ORDER BY ID DESC) " +
                "WHERE ROWNUM <= 1";

        try (Statement statement = Database.getConnection()
                .createStatement()) {
            ResultSet resultSet = statement.executeQuery(query);
            resultSet.next();
            album = new Album(resultSet.getInt(1),
                              resultSet.getString(2),
                              resultSet.getInt(3),
                              resultSet.getInt(4));
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return album;
    }

}
