package com.dao;

import com.app.Artist;
import com.util.Database;
import oracle.jdbc.internal.OracleStatement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class ArtistController {

    public boolean create(String name, String country) {
        boolean returnValue = true;
        try(PreparedStatement statement = Database.getConnection().prepareStatement("INSERT INTO artists VALUES(0, ?, ?)")) {
            // ID value generated by DBMS
            statement.setString(1, name);
            statement.setString(2, country);
            if(statement.executeUpdate() == 0) {
                returnValue = false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return returnValue;
    }

    public List<Artist> findByName(String name) {
        List<Artist> artists = new ArrayList<>();

        try(Statement statement = Database.getConnection().createStatement()) {
            Artist artist;
            ResultSet rs = statement.executeQuery("SELECT * FROM artists WHERE name = '" + name + "'");
            while(rs.next()) {
                artist = new Artist(rs.getInt(1), rs.getString(2), rs.getString(3));
                artists.add(artist);
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }

        return artists;
    }

    public Artist findByID(int artistID) {
        Artist artist = null;

        try(Statement statement = Database.getConnection().createStatement()) {
            ResultSet resultSet = statement.executeQuery("SELECT * FROM artists WHERE id = " + artistID);
            resultSet.next();
            artist = new Artist(artistID, resultSet.getString(2), resultSet.getString(3));
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return artist;
    }

    public Artist findLastAddedArtist() {
        Artist artist = null;
        String query = "SELECT * " +
                "FROM (SELECT * FROM artists ORDER BY ID DESC) " +
                "WHERE ROWNUM <= 1";

        try (Statement statement = Database.getConnection()
                .createStatement()) {
            ResultSet resultSet = statement.executeQuery(query);
            resultSet.next();
            artist = new Artist(resultSet.getInt(1),
                                resultSet.getString(2),
                                resultSet.getString(3));
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return artist;
    }

}
